version: '3'

services:
  wallet-service:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION_STRING=postgres://root:root@db:5432/wallet_db
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=wallet_db
    ports:
      - "5432:5432"